/**
 * Fish / relic image paths — prefer WebP (smaller) with PNG/JPG fallback.
 */

export function getFishImagePaths(fishName) {
    if (fishName === 'Starfish of Eternity') {
        return {
            primary: 'assets/images/StarfishofEternity.webp',
            fallback: 'assets/images/StarfishofEternity.jpg'
        };
    }
    const base = `assets/images/${fishName}`;
    return {
        primary: `${base}.webp`,
        fallback: `${base}.png`
    };
}

/** Relic art lives under images/hiddenitems/ — WebP siblings generated by compress-assets. */
export function getRelicImagePaths(pngOrWebpPath) {
    const fallback = pngOrWebpPath.replace(/\.webp$/i, '.png');
    const primary = fallback.replace(/\.(png|jpe?g)$/i, '.webp');
    return { primary, fallback };
}

/** @deprecated Use getFishImagePaths — PNG fallback for legacy callers */
export function getFishImagePath(fishName) {
    return getFishImagePaths(fishName).fallback;
}

/** Build img onerror handler for WebP → PNG/JPG fallback */
export function fishImageOnErrorAttr(fallbackSrc) {
    const safe = String(fallbackSrc).replace(/'/g, "\\'");
    return `onerror="if(!this.dataset.fallback){this.dataset.fallback='1';this.src='${safe}';}"`;
}

export function relicImageOnErrorAttr(fallbackSrc) {
    return fishImageOnErrorAttr(fallbackSrc);
}

/**
 * Warm browser + service-worker cache for image URLs without blocking the main thread.
 * @param {string[]} urls
 * @param {{ batchSize?: number, gapMs?: number }} options
 */
export function warmImageCache(urls, { batchSize = 6, gapMs = 100 } = {}) {
    const unique = [...new Set(urls.filter(Boolean))];
    if (!unique.length) {
        return Promise.resolve();
    }

    const run = async () => {
        for (let i = 0; i < unique.length; i += batchSize) {
            const batch = unique.slice(i, i + batchSize);
            await Promise.all(
                batch.map((url) => fetch(url, { credentials: 'same-origin' }).catch(() => null))
            );
            if (i + batchSize < unique.length && gapMs > 0) {
                await new Promise((resolve) => setTimeout(resolve, gapMs));
            }
        }
    };

    return run();
}

/** Collect primary WebP URLs for all fish + relic gallery images. */
export async function collectGalleryImageUrls() {
    const [{ FishTypes }, { HIDDEN_RELICS, STARLIGHT_LURE_IMAGE }] = await Promise.all([
        import('../fishTypes.js'),
        import('../config/hiddenRelics.js')
    ]);

    const urls = FishTypes.map((fish) => getFishImagePaths(fish.name).primary);
    HIDDEN_RELICS.forEach((relic) => urls.push(getRelicImagePaths(relic.image).primary));
    urls.push(getRelicImagePaths(STARLIGHT_LURE_IMAGE).primary);
    return urls;
}
